import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { ThemeProvider } from "@/components/theme-provider"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
      <main>
      <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
      >
        <nav>
            <Link href="/">Home</Link>
            <Link href="/resume">Resume</Link>
            {/* TODO: make a resume */}
            {/* TODO: add styling (tailwind!) */}
        </nav>
        {children}
      </ThemeProvider>
      </main>
      </body>
    </html>
  );
}